[project]
name = "disaster_backend"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "ortools",
  "numpy",
  "networkx>=3.4.2",
  "langchain-core>=0.3",
  "langchain-ollama>=0.2",
  "langgraph>=0.2",
  "httpx",
]
